"$schema" = 'https://starship.rs/config-schema.json'


format = """
[╭─](bold fg:lavender)\
$shell\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$line_break$character"""

# Catppuccin Macchiato palette
palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = true

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bold mauve"

[git_status]
style = "bold red"

[nodejs]
symbol = " "
style = "bold green"

[c]
symbol = " "
style = "bold blue"

[rust]
symbol = " "
style = "bold peach"

[golang]
symbol = " "
style = "bold sky"

[php]
symbol = " "
style = "bold mauve"

[java]
symbol = " "
style = "bold red"

[kotlin]
symbol = " "
style = "bold blue"

[haskell]
symbol = " "
style = "bold mauve"

[python]
symbol = " "
style = "bold yellow"

[docker_context]
symbol = " "
style = "bold sapphire"

[cmd_duration]
min_time = 1000
disabled = false
style = "bold peach"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format

[line_break]
disabled = false

[shell]
fish_indicator = '󰈺 '
zsh_indicator = ' '
bash_indicator = ' '
powershell_indicator = ' '
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'
xonsh_indicator = 'xsh'
cmd_indicator = ' '
nu_indicator = 'nu'
unknown_indicator = ' '
format = '[$indicator ]($style)'
style = "bold teal"
disabled = false

[character]
success_symbol = "[╰─⋗](lavender bold)"
error_symbol = "[╰─](lavender bold)"
disabled = false
