"$schema" = 'https://starship.rs/config-schema.json'


format = """
[╭─](bold fg:lavender)\
$shell\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$cmd_duration\
$line_break$character"""

# Catppuccin Mocha palette
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bold mauve"

[git_status]
style = "bold red"

[nodejs]
symbol = " "
style = "bold green"

[c]
symbol = " "
style = "bold blue"

[rust]
symbol = " "
style = "bold peach"

[golang]
symbol = " "
style = "bold sky"

[php]
symbol = " "
style = "bold mauve"

[java]
symbol = " "
style = "bold red"

[kotlin]
symbol = " "
style = "bold blue"

[haskell]
symbol = " "
style = "bold mauve"

[python]
symbol = " "
style = "bold yellow"

[docker_context]
symbol = " "
style = "bold sapphire"

[cmd_duration]
min_time = 1000
style = "bold peach"

[shell]
fish_indicator = '󰈺 '
zsh_indicator = ' '
bash_indicator = ' '
powershell_indicator = ' '
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'
xonsh_indicator = 'xsh'
cmd_indicator = ' '
nu_indicator = 'nu'
unknown_indicator = ' '
format = '[$indicator ]($style)'
style = "bold teal"

[character]
success_symbol = "[╰─⋗](lavender bold)"
error_symbol = "[╰─✗](red bold)"
